version: "3.9"

services:
  db:
    image: postgres:15
    container_name: contract_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manvi123
      POSTGRES_DB: contractdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: contract_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: manvi123
    ports:
      - "5050:80"

volumes:
  postgres_data:
