services:
  db:
    image: postgres:15
    container_name: lease_assistant_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lease_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ..
      dockerfile: backend/Dockerfile
    container_name: lease_assistant_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/lease_db

volumes:
  postgres_data: